### ISSUE TITLE
Stylus not working with the reader anymore?

### ISSUE THREAD

**Issue by aiko-tanaka** [ttu-ttu/ebook-reader#145]
Been using stylus to change font and background colors apart from those available by default, it did work before the new update.

Was trying to do something like

```css
:root {
	--background-color: rgb(180, 180, 180);
}

body {
    background-color: var(--background-color);
}
```
