### ISSUE TITLE
[Feature Request] Indentation at the beginning of each paragraph

### ISSUE THREAD

**Issue by steponmepls** [ttu-ttu/ebook-reader#228]
Ebook reader apps such as Moon Reader have this nice feature that adds an indentation at the beginning of each paragraph. Thankfully ttsu wraps them in `<p>` tags and correctly flags ones at the beginning of each chapter/section so I was able to add this feature with a simple CSS addition:
```css
section[id^="chapter"] > p:not(.noindent):not(.cotx):not([class^="space-break"]) {
  text-indent: 2em;
}
```

It would be nice to see this implemented in the configuration panel or maybe on a per-book basis. And maybe with an option to use a custom indentation unit. I used `2em` because it looked good enough for me.

![image](https://github.com/ttu-ttu/ebook-reader/assets/63500907/9e31b50f-a83e-4775-b557-cec15833b6df)
